server:
  port: 8100
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: server
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis-plus:
  type-aliases-package: com.example.modules.**.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

sa-token:
  is-print: false
  token-name: Authorization
